### ISSUE TITLE
Accounts created for stock Embedded Finance demo don't have card_payments capability enabled

### ISSUE THREAD

**Issue by sperand-io** [stripe-samples/issuing-treasury#298]
# Bug report

## Describe the bug

Payment link discovered in Test Data pane fails due to inactive capability

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

0. Find the (awesome) demo **[here](https://docs.stripe.com/baas/start-integration/sample-app)**
1. Onboard fresh with fake credentials
2. Go to test-data pane
3. Create payment link and navigate to it
4. Attempt payment
5. See this

<img width="415" alt="image" src="https://github.com/stripe-samples/issuing-treasury/assets/3130232/431a210a-8df0-4a11-8aec-77f1ea145423">

## Expected behavior

Card payments capability is requested at account creation time and the user can accept payments and sweep them to their FA

https://github.com/stripe-samples/issuing-treasury/blob/423d76731f4795542781df8f135b8d6e8edf5e6a/embedded-finance/src/pages/api/register.ts#L62-L70

## Additional context

I'd consider changing this section from "test data" to "payments" as all functionality relates to payment processing and it stands to help folks understand the critical distinction between their CA payments balance and FA. 

Happy to make a PR here— lmk!

**Comment by snasir-stripe** [comment]
Thanks for filing this @sperand-io. We've actually been in talks to simplify this demo and remove the payments features. The internal feedback I've received is that it's even more confusing on the expense management (UK, Issuing only) variant that we recently added. Seeing two balances in the home page. A while ago, I removed the `card_payments` capability request in this code you linked to demonstrate that we only need `card_issuing` and `transfers`, and `treasury` for FAs. But I should have removed this Test Data page because it's pretty much useless.

Do you find the Test Data payments features as part of the demo helpful for understanding how one can create a payout? I'm wondering if it's worth keeping and we bring back the `card_payments` capability.

**Comment by sperand-io** [comment]
Sorry for the slow response, and thanks for getting back! I think it may make sense to remove it given the focus of the demo, but that would depend on how common it is for vertical saas and neobank type users to build out the commercial treasury functionality without payments as a starting point. IMO— the distinction between connected account payments balances and financial accounts is subtle enough that it may be helpful to have flows that call attention to that in the sample.

**Comment by snasir-stripe** [comment]
Np! Okay I'm going to bring it back in and retroactively request the `card_payments` capability for all the existing accounts. So that Test Data page should start working again for everyone. Sorry for the trouble! I'll also rename that page to something more appropriate at some point in the next few weeks.

**Comment by snasir-stripe** [comment]
https://github.com/stripe-samples/issuing-treasury/pull/305

**Comment by sperand-io** [comment]
Awesome! Sg. Thanks for the quick response— fft to close!
