### ISSUE TITLE
card_issuing can only be requested if your platform has been onboarded on Stripe Issuing already.

### ISSUE THREAD

**Issue by techtic-naman** [stripe-samples/issuing-treasury#46]
In your repository, I will use test mode in Stripe. but I got this error. if I need to create an account using your repo so is it compulsory to create a card issuing? please help me. thanks...

**Comment by snasir-stripe** [comment]
Hi @techtic-naman 👋. This repository has been re-written since you last used it. Are you still having issues?

**Comment by BrunoAwdd** [comment]
Hi. I have the same problem

**Comment by snasir-stripe** [comment]
Hi @BrunoAwdd and @techtic-naman. Can you help me understand the problem a bit more? This repo is designed and tested to work with Issuing and Treasury testmode. There is only one way to trigger this error:

```
card_issuing can only be requested if your platform has been onboarded on Stripe Issuing already.
```

And that is if the platform account (your Stripe account) is not actually onboarded onto Issuing. Just like how you're probably requesting the `card_issuing` capability on a test connected account, the same capability must first be active on the platform account itself. If you feel comfortable sharing your platform account token, I can take a look and see whether or not it's in a weird state. But otherwise, my recommendation would be to ensure you've onboarded onto Issuing testmode.

What do you see when you go to this link in your dashboard? 
<img width="340" alt="image" src="https://github.com/stripe-samples/issuing-treasury/assets/103917180/eb223757-353e-4f63-9fb2-8a0e053a1c56">
Does it show a plus symbol with a circle next to "Issuing"?

**Comment by snasir-stripe** [comment]
We've updated our [docs here](https://stripe.com/docs/baas/start-integration/sample-app?ui=copy-sample-app&copy-sample-app-tabs=demo-app-repo#before-you-begin) to provide a checklist of things that need to be met in order to use the sample app with your own platform. Hoping this helps resolve this issue. Feel free to open another issue if you folks are having trouble still.
